### ISSUE TITLE
브리핑 요청: users>views.py>profile>password change 관련부분

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#15]
https://github.com/ESTsoft-Book-Project/bookstore/blob/47a76c2787bd9a128b7dfe9f009fcf2749749994/users/views.py#LL45C25-L45C26

[update_session_auth_hash](https://docs.djangoproject.com/en/4.2/topics/auth/default/#django.contrib.auth.update_session_auth_hash) 함수는 변경된 유저정보가 포함된 요청을 바탕으로 새 세션 키를 할당합니다. 일종의 보안 관련 코드인 것 같은데, [set_password](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.set_password)와의 차이점이 어떻게 되는지 궁금합니다.

**Comment by allen9535** [comment]
set_password의 경우 사용자의 비밀번호만 변경하는 함수입니다. 그래서 해당 함수만 사용하여 비밀번호 변경을 시도할 경우, 기 인증된 사용자의 상태와 달라지기 때문에 로그아웃 하게 됩니다. update_session_auth_hash 함수를 함께 사용할 경우 기 인증되었던 세션에서 비밀번호가 변경된 세션으로 갱신해주기 때문에 로그인 상태를 유지할 수 있게 됩니다.
