### ISSUE TITLE
DRF 적용 시 추가되는 의존성을 requirements.txt로

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#29]
근데 @iankimdev 님, 궁금한게 하나 있어요. 저는 현재 pip로 pylint-django를 추가로 설치해서 사용하고 있는데, 사실 프로젝트 단에서 보면 불필요한 의존성이란 말이죠. 이걸 그냥 깃허브에 올려야 하나 필수 의존성만 올려야 하나 고민입니다.

만약 필수 의존성만 올려야 한다면 불필요한 의존성을 .gitignore처럼 제외하고 requirements.txt를 수정하는 방법 없을까요?

**Comment by ChoiWheatley** [comment]
[pipreqs](https://betterdatascience.com/python-pipreqs/#:~:text=Pipreqs%20works%20by%20scanning%20all.py%20files%20in%20a,a%20Python%20project%20folder%2C%20simply%20run%20this%20command%3A)는 프로젝트의 모든 `.py` 파일을 읽은 뒤 실제로 필요한 의존성만을 출력한다고 합니다.

**Comment by iankimdev** [comment]
pylint_django가 필수적이지 않다고 생각하면 제외하는 것이 나을듯합니다. 
requirements.txt파일에서 pylint_django 부분을 주석처리하면 됩니다.
