### ISSUE TITLE
#35 update date 적용

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#37]
현재는 책 정보를 수정해도 '수정일'이 변화하지 않는다.

**Comment by iankimdev** [comment]
제가 products 모델 설계부분에서 created와 updated를 동일하게 작성하였기 때문입니다. 이도님께 수정 후 커밋 요청하였습니다

수정 전
created = models.DateTimeField(auto_now_add=True)
updated = models.DateTimeField(auto_now_add=True)

수정 후
created = models.DateTimeField(auto_now_add=True)
updated = models.DateTimeField(auto_now=True)
