### ISSUE TITLE
인가되지 않은 유저의 책 정보 수정 방지

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#46]
현재 아무 유저나 `<domain>/products/book/update<slug>`에 들어가 수정하고 등록자를 바꿀 수 있는 버그가 존재합니다. 인가와 관련한 코드는 #16 을 참조하시기 바랍니다. 아마도 [user_passes_test](https://docs.djangoproject.com/en/4.2/topics/auth/default/#limiting-access-to-logged-in-users-that-pass-a-test) 데코레이터를 사용하면 될 것입니다.

https://github.com/ESTsoft-Book-Project/bookstore/blob/0667d3eeded26793efe96c0f0243096822fb13dd/products/views.py#L43C1-L72

**Comment by ChoiWheatley** [comment]
와! 자동으로 이슈가 닫힌다!!

**Comment by iankimdev** [comment]
{% if book.user == request.user %}를 도입하면서 user를 확인하는 코드로 PR#48에서 해결됨

**Comment by ChoiWheatley** [comment]
큰일입니다. 인가되지 않은 유저가 book_detail에 들어가면 `deleteBtn`가 없는 것 까지는 좋은데, JS 단에서 null에 `addEventListner` 메서드를 호출했다는 오류가 발생했습니다. css hidden을 사용하는 방법이 좋을 듯 합니다

https://github.com/ESTsoft-Book-Project/bookstore/blob/017f4701c0b4b8eab5b03edce10ab61f32bab937/templates/book_detail.html#L38

```
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at (index):84:45
```

**Comment by iankimdev** [comment]
```javascript
const deleteBtn = document.getElementById('deleteBtn');
if (deleteBtn) {
  deleteBtn.addEventListener('click', function (e) {
    // 삭제 버튼의 동작
  });
}
```
로 수정하면 될 것 같습니다. 미팅 때 수정해보죠
