### ISSUE TITLE
getCookie 중복제거

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#47]
1. https://github.com/ESTsoft-Book-Project/bookstore/blob/0667d3eeded26793efe96c0f0243096822fb13dd/templates/signup.html#L73
2. https://github.com/ESTsoft-Book-Project/bookstore/blob/0667d3eeded26793efe96c0f0243096822fb13dd/templates/update_product.html#L46
3. https://github.com/ESTsoft-Book-Project/bookstore/blob/0667d3eeded26793efe96c0f0243096822fb13dd/templates/create_product.html#L46
4. https://github.com/ESTsoft-Book-Project/bookstore/blob/0667d3eeded26793efe96c0f0243096822fb13dd/templates/book_detail.html#L18

`getCookie` 함수 선언, `csrf_token = getCookie()` 구문은 전부 base.html 안에 들어있습니다. 장고 템플릿을 통하여 확장하였기 때문에 더 이상 `getCookie` 함수를 선언할 필요가 없습니다.

**Comment by ChoiWheatley** [comment]
중복으로 인해 발생하는 버그는 nav bar `SignOut` 관련 스크립트가 실행되지 않아 JSON이 그대로 브라우저에 찍히는 문제가 있습니다.

**Comment by iankimdev** [comment]
승현님이 코드 정리 후 PR 예정입니다.
