### ISSUE TITLE
requirements 이슈

### ISSUE THREAD

**Issue by allen9535** [ESTsoft-Book-Project/bookstore#51]
https://github.com/ESTsoft-Book-Project/bookstore/blob/017f4701c0b4b8eab5b03edce10ab61f32bab937/requirements.txt#L8-L11
python-slugify가 서로 다른 버전으로 두 개 있습니다.(8.0.1 / 8.0)
requirements.txt 내용을 다운로드 하면 에러가 발생합니다.

**Comment by ChoiWheatley** [comment]
헉

**Comment by nohheeyeon** [comment]
이거 제가.. 실수로 PR하지않고, 바로 수정 뒤 main에 push하였습니다.. 일단 해결은 됐으니 이슈닫도록 하겠습니다..!
