### ISSUE TITLE
tracking(oauth): Error tracking issue

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#63]
안녕하세요! 오늘 OAuth 진행에 많은 도움을 주셔서 감사합니다! 👍  책 집필 내용에 OAuth에서 문제가 발생했던 부분들과 그 해결방법에 대해서 작성하려고 합니다. 오늘 많은 사람들이 고통받았던 Redirect URI를 포함한 다양한 문제상황에 대하여 생각나시는 대로 아래 스레드에 답글 달아주시면 감사하겠습니다!

**Comment by Water-Stone** [comment]
- Redirect URI를 입력할 때 `http://localhost:8000`가 아니라 `http://127.0.0.1:8000`으로 해야합니다.
    -    둘의 차이점? 참고: https://www.baeldung.com/cs/127-0-0-1-vs-localhost
    > More often than not, localhost and 127.0.0.1 are used interchangeably. The two are considered the same thing. However, there are subtle differences that exist between them. Let’s look at these:
Firstly, the IP address associated with localhost has to be resolved or looked up, while 127.0.0.1 does not usually require resolution.
Secondly, localhost is not always resolved to 127.0.0.1. It may be resolved to another address within the loopback block of addresses.

**Comment by kim-ido** [comment]
- 커스텀 User 모델을 사용할 때 에러

`allauth` 라이브러리의 기본 설정은 표준 User 모델을 대상으로 하기 때문에
커스텀 User 모델을 사용 중인 경우에는 그에 맞게 라이브러리 설정값을 변경해주어야 합니다.
별도로 설정을 하지 않고 소셜로그인을 구현했을 때에는 아래와 같은 에러를 만나게 됩니다.

>![image](https://github.com/ESTsoft-Book-Project/bookstore/assets/96900790/fed738a6-7ee2-4f57-a8bf-e3508bbd2430)

내용을 보면 `User` 객체에 `username` 속성이 존재하지 않기 때문에 문제가 발생합니다.
위의 에러를 해결하기 위해서는 아래와 같이 `allauth` 라이브러리 설정을 변경해 줄 필요가 있습니다.
(User 모델이 `USERNAME_FIELD = "email"`로 설정되어 있는 경우를 가정합니다.)
> settings.py
![image](https://github.com/ESTsoft-Book-Project/bookstore/assets/96900790/36f597a5-36e7-47e4-aaea-5bec3a7471af)

`ACCOUNT_EMAIL_REQUIRED = True`
: 이 설정을 `True`로 변경하면 사용자의 이메일 주소를 회원가입 시 필수 필드로 지정합니다.

`ACCOUNT_AUTHENTICATION_METHOD = 'email'`
: 사용자 인증 방법으로 이메일을 사용하도록 변경합니다.
이 설정을 `email`로 변경하려면 `ACCOUNT_EMAIL_REQUIRED = True`가 필요합니다.

`ACCOUNT_USERNAME_REQUIRED = False`
: username 필드를 필수 필드로 지정하지 않음을 나타냅니다.
이렇게 설정 해줌으로써 username 필드를 입력받지 않고도 회원가입이 가능하게 됩니다.

`ACCOUNT_USER_MODEL_USERNAME_FIELD = None`
: 이 설정은 User 모델의 username 필드를 지정하는 옵션입니다. 기본값은 username이기 때문에 위의 
`ACCOUNT_USERNAME_REQUIRED` 설정을 `False`로 바꾸어도 username 필드를 찾습니다.
값을 `None`으로 변경하면 username 필드를 찾지 않고, 이메일을 사용하여 User를 식별합니다.
이 설정을 위와 같이 변경하려면 `ACCOUNT_USERNAME_REQUIRED = False`가 필요합니다.

ref: https://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by kim-ido** [comment]
## SITE_ID 관련 에러: Site matching query does not exist

> ![image](https://github.com/ESTsoft-Book-Project/bookstore/assets/96900790/8d731a4d-5212-40da-8586-0e9094f774d6)

### 발생 경위
해당 에러는 요청에 대한 사이트와 일치하는 쿼리가 존재하지 않음을 나타냅니다.
`SITE_ID`가 잘못 설정되거나 `django_site` 테이블에 해당 사이트 정보가 없을 경우, 관련된 에러가 발생할 수 있습니다.
`SITE_ID`는 장고 프로젝트에서 여러 사이트를 관리할 때 사용되는 변수라고 합니다.

Sites 탭에서 기본값으로 존재하던 example.com 값을 수정하는 것이 아닌 값을 새로 만든 후에
example.com을 삭제하고 소셜 로그인을 시도하면 위와 같은 에러를 만나게 됩니다.
(id값이 2인 127.0.0.1 추가되고, id값이 1인 example.com 삭제되면서 에러가 발생)

## 해결

> ![image](https://github.com/ESTsoft-Book-Project/bookstore/assets/96900790/ce72fff1-bb71-44df-96d5-038aa6c2fbf6)

> settings.py
> ![image](https://github.com/ESTsoft-Book-Project/bookstore/assets/96900790/d3cab906-cb5b-4338-9b82-bec66778a379)

`django_site` 테이블에서 사이트의 id값을 확인합니다.
해당 값을 `SITE_ID`에 저장해주면 에러가 해결됩니다!
사실 테이블 확인 안 하고 `SITE_ID` = 1일 경우 에러가 난다면 2 또는 3으로 바꿔주면 해결된다고 합니다.
