### ISSUE TITLE
Carts' Goal

### ISSUE THREAD

**Issue by taencoding** [ESTsoft-Book-Project/bookstore#72]
pr #71 

## 구현O
 1. 장바구니 페이지
    - 주문하기 누르면 주문 상세 페이지로 리다이렉트
 2. 주문 상세 페이지
    - 테이블 : 상품명, 수량, 상품 별 1개 가격, 이미지, 상품별 총 금액
    - 모든 상품 총액
    - 주문자 정보 : user , nickname, email
    - 결제수단 선택 : stripe, kakaopay
    - 결제 취소 -> 장바구니로 리다이렉트

## 해야 할 것
1. 선택된 상품들만 상세페이지로 보내기
    - [x] 현재 상품들은 기본으로 `checked=False` 되어 있음
    - [x] checked 상품을 checked=True 로 저장하여, `Cart.objects.filter(user=request.user, checked=True)` 에서 걸러지기
2. 수량이 1개로만 설정됨
    - [x] 변경된 수량을 넘겨 orderItem.js 파일의 `item['quantity']` 값으로 저장되어야 함
3. 모든 상품 총액
    - [x] 모든 상품들의 총액이 0으로 표시됨
    - [x] 모든 checked 상품들의 총액을 표시
4. 결제수단 누르면 결제하기
    - [x] stripe 연동 필요
    - [x] kakaopay 연동 필요

**Comment by ChoiWheatley** [comment]
Goal 추가

- [ ] 결제 완료시, 해당 유저의 Cart를 모두 제거
