### ISSUE TITLE
bug(users): Signout error (GET /users/signout/ HTTP/1.1")

### ISSUE THREAD

**Issue by iankimdev** [ESTsoft-Book-Project/bookstore#74]
signout 시 405 에러를 일으킴.

![Screen Shot 2023-06-24 at 17 08 10](https://github.com/ESTsoft-Book-Project/bookstore/assets/120093816/9479dd4d-f9cd-4f31-8df9-ae8f695bc8a8)

(추가) google login 시 프로필 페이지로 리다이렉트가 안됨(캐시의 문제로 추측됨)

**Comment by ChoiWheatley** [comment]
profile 페이지에서 signout 시 발생함.

**Comment by ChoiWheatley** [comment]
navbar의 `signout_out_btn`은 POST 요청인데 `users.signout` 함수가 GET만을 받고있어 method not allowed 에러가 발생합니다. 이슈 다시 열겠습니다.
