### ISSUE TITLE
cart, order 함수명 리팩토링 필요

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#79]
- 이름을 좀 더 semantic하게...
	- `cart_list` => render
		- `carts/view`
	- `product_list` => jsonresponse
		- `carts/list`
- order_detail도 이름을 좀 더 semantic하게...
	- `order_detail` => render
		- `carts/checkout/view`
	- `order_product_detail` => jsonresponse
		- `carts/checkout/list`

_Originally posted by @iankimdev in https://github.com/ESTsoft-Book-Project/bookstore/pull/78#pullrequestreview-1496899708_

**Comment by iankimdev** [comment]
#84 에서 해결하였습니다.
