### ISSUE TITLE
Error : no such column: purchases_purchase.order_name

### ISSUE THREAD

**Issue by iankimdev** [ESTsoft-Book-Project/bookstore#80]
navbar orders 클릭 시 발생 에러 
"GET /purchases/orders/ HTTP/1.1" 500 

![Screen Shot 2023-06-25 at 14 45 30](https://github.com/ESTsoft-Book-Project/bookstore/assets/120093816/36779835-a761-4a2a-9511-699167e74163)

**Comment by iankimdev** [comment]
Order cancle 로직까지 정상 작동했는데 PR후 동작하지 않는 것으로 보입니다.

**Comment by iankimdev** [comment]
마이그레이션에 order_name이 추가되었는데 광호님의 커밋에서 그부분이 누락된 것에 대한 충돌인 것 같습니다.

**Comment by ChoiWheatley** [comment]
배포단계에 도달하면 마이그레이션을 전부 0001로 만드는 것이 정신건강에 이롭겠군요

**Comment by ChoiWheatley** [comment]
> 마이그레이션에 order_name이 추가되었는데 광호님의 커밋과의 대한 충돌인 것 같습니다.
> 
> Carts, Products, Purchases model migrations파일 삭제, DB삭제 후 Re-migrations and migrate 하면 충돌이 해결됩니다.

여기에 추가로 DB 삭제 시 Social applications또한 날아가기 때문에 OAuth를 위해서라면 다시 admin 페이지로 들어가 세팅해주어야 합니다.

1. http://127.0.0.1:8000/admin/sites/site/ 로 들어가 Domain name을 `example.com` → `127.0.0.1`로 변경
2. http://127.0.0.1:8000/admin/socialaccount/socialapp/ 으로 들어가 Naver, Kakao, Google에 대한 클라이언트 id, 시크릿 키, Chosen Sites를 모두 설정하시기 바랍니다. 관련 대화는 #63 에 있습니다.
